Starting translation
ukrainian-carpentries/workshop-template pull request #1
Opened 2024-03-15 10:53 UTC by VeronikaShevc

2024-03-15 10:55 UTC, olexandr-konovalov commented on index.md
> +layout: workshop      # Цей текст не можна змінювати.
@VeronikaShevc thanks, this is a good start!!!

2024-04-23 12:48 UTC, olexandr-konovalov commented
@VeronikaShevc preview of your work is at https://veronikashevc.github.io/workshop-template/ - saving the link in the comment to find it quickly next time.

2024-04-23 12:55 UTC, olexandr-konovalov reviewed
Well done @VeronikaShevc - keep up good work!

2024-04-23 12:55 UTC, olexandr-konovalov commented on index.md
> +Поясніть, хто ваша аудиторія.  (Зокрема, повідомте аудиторії, чи семінар відкритий лише для людей з певної установи.
missing matching ")"

2024-04-23 12:55 UTC, olexandr-konovalov commented on index.md
> +АУДИТОРІЯ
Я б сказав "ЦІЛЬОВА АУДИТОРІЯ", щоб уникнути непорозумінь - це не номер лекційної аудиторії в університеті.

2024-04-23 12:55 UTC, olexandr-konovalov commented on index.md
> +- Цей семінар відкритий для осіб у партнерських выдносинах з університетом ABC.
"відносинах"

2024-04-23 12:55 UTC, olexandr-konovalov commented on index.md
> +  Щоб дізнатися більше про ролі на семінарі (хто що робитиме), зверніться до нашої платформи Workshop FAQ<a href="https://carpentries.org/workshop_faq/#what-are-the-roles-of-everyone-participating-in
"зверніться до Workshop FAQ" мабуть?

2024-04-23 12:55 UTC, olexandr-konovalov commented on index.md
> +КОНТАКТНА АДРЕСА ЕЛЕКТРОННОЇ ПОШТИ
"АДРЕСА ЕЛЕКТРОННОЇ ПОШТИ ДЛЯ КОНТАКТІВ" ?

2024-04-29 13:14 UTC, olexandr-konovalov commented
After index.html, next steps are:
- https://github.com/ukrainian-carpentries/workshop-template/blob/gh-pages/_includes/install_instructions/shell.html
- https://github.com/ukrainian-carpentries/workshop-template/blob/gh-pages/_includes/install_instructions/git.html
- https://github.com/ukrainian-carpentries/workshop-template/blob/gh-pages/_includes/install_instructions/python.html

2024-05-04 16:32 UTC, olexandr-konovalov commented on index.md
> +УВАГА: ви визначили власні посилання до та/або після опитування для семінару, який не налаштований для The Carpentries Incubator (значення 'curriculum' не встановлено на 'incubator' у '_config.yml').
@VeronikaShevc please use same kinds of quotes, don't replace them by "fancy quotes" like «carpentry»

2024-05-04 16:34 UTC, olexandr-konovalov commented on index.md
> +  `_includes/custom-schedule.html`. Додайте до цього файлу час і те, чого ви будете навчати. Ви також можете додати рядки до таблиці, якщо хочете розбити розклад далі. Щоб використовувати цей користу
Not very critical, but using hard line breaks in the long run makes inspecting changes and resolving conflicts easier. Try to not to use long lines in subsequent translations please.

2024-05-04 16:43 UTC, olexandr-konovalov requested changes
Гарний старт - дякую @VeronikaShevc! Я ось що думаю - інсталятор англомовний, тому коли читачі побачать переклади усіх опцій, їм буде треба потім зʼясувати, а як же вони будуть англійською. З іншого боку, ми бажаємо пояснювати, що саме ці опції значать. Давайте оберемо формат, коли спочатку пишеться англійський текст, а потім у дужках - його пояснення українською.  

Наприклад:

- Вам не потрібно нічого змінювати на екранах "Information" (Iнформація"), "Location" (Розташування). ....

- На сторінці з написом "Adjusting the name of the initial branch in new repositories" (Коригування назви початкової гілки в нових репозиторіях") переконайтеся, ...

До речі, використовуйте стандартні подвійні лапки "..." замість «...» (десь у редакторі або операційній системі налаштовується).

2024-05-07 12:53 UTC, olexandr-konovalov commented on _includes/install_instructions/python.html
> +            (або <kbd>Return</kbd> залежить від клавіатури).
мабуть "у залежності від клавіатури" або "залежно від клавіатури"

2024-05-07 12:56 UTC, olexandr-konovalov commented on _includes/install_instructions/python.html
> +            (це робить розподіл Anaconda типовим Python).
мабуть "тоді за замовчуванням буде використовуватися Python з дистрибутиву Anaconda"  ?

2024-05-07 12:57 UTC, olexandr-konovalov commented on _includes/install_instructions/python.html
> +          <li>Завантажте інсталятор Anaconda з Python 3 для macOS (ви можете використовувати графічний або інсталятор командного рядка).</li>
мабуть "ви можете використовувати інсталятор який використовує графічний інтерфейс користувача або командний рядок"

2024-05-07 12:59 UTC, olexandr-konovalov commented on _includes/install_instructions/python.html
> +            щоб схвалити ліцензію.
"щоб погодитися з ліцензією"

2024-05-11 12:48 UTC, olexandr-konovalov commented
Дуже добре - дякую @VeronikaShevc! Наступні кроки - дивлячись на https://veronikashevc.github.io/workshop-template/, бачимо, що ще не вистачає цих двох:
- https://github.com/ukrainian-carpentries/workshop-template/blob/gh-pages/_includes/install_instructions/editor.html
- https://github.com/ukrainian-carpentries/workshop-template/blob/gh-pages/_includes/install_instructions/r.html

2024-05-14 19:18 UTC, VeronikaShevc commented
I think I`m finished with translating editor and r. What should I translate next?

2024-05-15 07:24 UTC, olexandr-konovalov commented
@VeronikaShevc great, thanks! Please check https://veronikashevc.github.io/workshop-template/, see what else is not translated, try to find it's source in the repository. For example, the schedule is in https://github.com/ukrainian-carpentries/workshop-template/blob/gh-pages/_includes/swc/schedule.html

2024-05-16 19:41 UTC, VeronikaShevc commented
I think, I`m done with the web-page. I translated the main texts and the attached ones. Can you please check, if I`ve done it correctly. 
Thank you

2024-05-16 21:21 UTC, olexandr-konovalov commented
@VeronikaShevc thanks! Will try to review on Friday.

2024-05-18 09:24 UTC, olexandr-konovalov commented on _includes/install_instructions/editor.html
> +    зазвичай Vim, який не славиться своєю інтуїтивністю та зрозумілистю.
-> зрозумілістю

2024-05-18 09:26 UTC, olexandr-konovalov commented on _includes/install_instructions/editor.html
> +    написання коду, з такими функціями, як автоматичне кольорове кодування
кодування -> підсвічування

2024-05-18 09:30 UTC, olexandr-konovalov commented on _includes/install_instructions/editor.html
> +          nano є базовим редактором і типовим редактором, який інструктори
basic -> елементарний, простий

2024-05-18 09:31 UTC, olexandr-konovalov commented on _includes/install_instructions/editor.html
> +          nano є базовим редактором і типовим редактором, який інструктори
типовим -> основним

2024-05-18 09:31 UTC, olexandr-konovalov commented on _includes/install_instructions/editor.html
> +          nano є базовим редактором і типовим редактором, який інструктори
також ще два рази нижче

2024-05-18 09:32 UTC, olexandr-konovalov commented on _includes/install_instructions/git.html
> +Інструкції з налаштування Git базуються на інструкціях Shell.
інструкціях для Shell

2024-05-18 09:33 UTC, olexandr-konovalov commented on _includes/install_instructions/git.html
> +Якщо ви не приєднуєте інструкції Shell на веб-сайт семінарі,
Якщо ви не додаєте ... до...

2024-05-18 09:35 UTC, olexandr-konovalov commented on _includes/install_instructions/git.html
> +          Git має бути встановлено на вашому комп'ютері як частину
буде встановлено

2024-05-18 09:41 UTC, olexandr-konovalov requested changes

2024-05-18 09:41 UTC, olexandr-konovalov commented on _includes/install_instructions/git.html
> +          доведеться клацнути правою кнопкою миші (клацнути кермом) на
мається на увазі що можна натиснути Control та клацнути

2024-05-18 09:41 UTC, olexandr-konovalov commented on _includes/install_instructions/git.html
> +          нічого не буде, оскільки Git є програмою командного рядка.
програмою, яка використовується за допомогою командного рядка

2024-05-18 09:41 UTC, olexandr-konovalov commented on _includes/install_instructions/git.html
> +          найновіший доступний інсталятор з позначкою "snow-leopard", доступний
найновіший -> останній

2024-05-18 09:41 UTC, olexandr-konovalov commented on _includes/install_instructions/git.html
> +          допомогою менеджера пакунків вашої розсилки. Для запуску Debian/Ubuntu
менеджера пакетів вашого дистрибутива

2024-05-18 09:41 UTC, olexandr-konovalov commented on _includes/install_instructions/git.html
> +          <code>sudo apt-get install git</code> і для запуску Fedora
видаліть двічі слово "запуску"

2024-05-18 09:41 UTC, olexandr-konovalov commented on _includes/install_instructions/python.html
> +Видаліть третій абзац, якщо семінар буде навчати Python
якщо на семінарі буде викладатись...

2024-05-18 14:02 UTC, olexandr-konovalov requested changes
Наступна порція - буде ще

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/python.html
> +    <a href="https://python.org">Python</a> це популярна мова для
додайте " - " перед "це"

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/python.html
> +          <li>Завантажте Python 3, запустивши інсталятор Anaconda, використовуючи всі значення за
Завантажте Python 3 -> Встановіть Python 3

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/python.html
> +          <li>Завантажте Python 3, запустивши інсталятор Anaconda, використовуючи всі значення за
використовуючи для встановлення всі значення за замовчуванням

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/python.html
> +          <li>Встановіть Python 3, запустивши інсталятор Anaconda, використовуючи всі значення за
використовуючи для встановлення всі значення за замовчуванням

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/python.html
> +            (оді за замовчуванням буде використовуватися Python з дистрибутиву Anaconda).
тоді

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/r.html
> +          пізніше, наприклад, при встановленні пакунків R.
пакунків -> пакетів

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/r.html
> +          скористатися вашим менеджером пакунків (наприклад, для Fedora
пакунків -> пакетів

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +                  (Вибір редактора за замовчуванням, що використовується Git) виберіть
Вибір редактора, що використовується Git за замовчуванням

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +                все ще використовує стару парадигму.
Мені здається, що цей коментар вже застарілий - мабуть його треба вдалити з англійської версії

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +                Виберіть "Use bundled OpenSSH" (Використовувати комплектний OpenSSH).
комплектний OpenSSH -> OpenSSH з цього дистрибутиву

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +                (Використовувати рідну бібліотеку захищених каналів Windows), і натисніть "Next" (Далі).
рідну -> вбудовану

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +              {% comment %} Це означає, що люди, які застрягли за корпоративними брандмауерами,
застрягли  -> знаходяться

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +              які здійснюють атаки MITM за допомогою свого власного кореневого СА (Цифровий сертифікат),
MITM (man-in-the-middle) атаки

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +              все ще можуть отримати доступ до віддалених репозиторіїв git. {% endcomment %}
можуть -> зможуть

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +                (Перевірити у стилі Windows, зафіксувати закінчення рядків у стилі Unix) і
працювати у стилі Windows, зберігати у стилі Unix

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +                (Увімкнення кешування файлової системи), і натисніть "Next" (Далі).
Увімкнення -> дозволити

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +            Якщо вашу змінну середовища "HOME" (ГОЛОВНА СТОРІНКА) не встановлено (або ви не знаєте, що це таке):
Головна сторінка -> домашній каталог

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +                Введіть наступний рядок у вікно командного рядка точно так, як показано:
точно так -> саме так (?)

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +          Оболонка за замовчуванням в Mac OS X Ventura і більш нових версіях - є Zsh,
є -> це

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +          Можливо, ви захочете закріпити Термінал на для цього семінару.
... на панелі задач для...

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +            Щоб перевірити, чи є ваша типова оболонка Bash, введіть <code>echo $SHELL</code>
що Bash є вашою оболонкою за замовчуванням

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +          і натисніть клавішу <kbd>Return</kbd>, а потім перезавантажтеся, щоб зміни набули чинності.
а потім перезавантажте компʼютер

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +          <kbd>Return</kbd> і перезавантажтеся. Щоб перевірити доступні оболонки, введіть
і перезавантажте компʼютер

2024-05-18 14:02 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +          <kbd>Return</kbd> і перезавантажтеся. Щоб перевірити доступні оболонки, введіть
також ще два рази нижче

2024-05-18 14:17 UTC, olexandr-konovalov requested changes
Мабуть на сьогодні усе. Коли все виправите, буде готово для злиття з основним репозиторієм. Після  злиття запросимо інших перекладачів для подальшої перевірки!

2024-05-18 14:17 UTC, olexandr-konovalov commented on _includes/swc/intro.html
> +    "<a href="https://doi.org/10.1371/journal.pbio.1001745">Найкращі практики наукових обчислень</a>".
практики для... - також це назва статті, дайте її англійською, а переклад у дужках

2024-05-18 14:17 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +            Щоб перевірити, чи є ваша типова оболонка Bash, введіть <code>echo $SHELL</code>
те ж саме ще декілька разів нижче

2024-05-18 14:17 UTC, olexandr-konovalov commented on _includes/swc/intro.html
> +  з меншими проблемами, навчаючи їх базовим навичкам дослідницьких обчислень.
наукових обчислень (?)

Також назва статті нижче використовує

2024-05-18 14:17 UTC, olexandr-konovalov commented on _includes/swc/intro.html
> +  отримані знання на власних дослідницьких проблемах.
на   -> для власних дослідницьких проблем.

2024-05-18 14:17 UTC, olexandr-konovalov commented on _includes/swc/who.html
> +    Вам не потрібно мати жодних попередніх знань про інструменти,
інструменти -> програми

2024-05-18 14:17 UTC, olexandr-konovalov commented on index.md
> +<a href="{{site.lc_site}}">Library Carpentry</a> спільноти інструкторів, тренерів, супроводжувачів, помічників і прихильників. Вони мають спільну місію — навчати дослідників базовим навичкам обчислен
"обчислення та наукам про дані." - треба краще сформулювати

2024-05-18 14:17 UTC, olexandr-konovalov commented on index.md
> +  Матеріали будуть надані до початку семінару. А нотатки з великим шрифтом доступні за потреби, заздалегідь попередивши про це організаторів. Якщо ми можемо допомогти вам полегшити навчання (наприкла
Не починайте речення з "А"

2024-05-18 14:17 UTC, olexandr-konovalov commented on index.md
> +  Ми не вимагаємо від учасників надавати документи про інвалідність або розкривати будь-яку непотрібну особисту інформацію. Однак ми хочемо допомогти створити інклюзивний, доступний досвід для всіх у
особисту інформацію, яку ми не потребуємо

2024-05-18 14:17 UTC, olexandr-konovalov commented on index.md
> +- Цей семінар відкритий для осіб у партнерських відносинах з університетом ABC.
для студентів та співробітників університету ABC

2024-05-18 14:17 UTC, olexandr-konovalov commented on index.md
> +- рекомендації щодо облаштування робочого простору учнів, щоб вони могли слідувати інструкціям та відеоконференціям
учнів -> слухачів

2024-05-18 20:26 UTC, olexandr-konovalov commented on _includes/install_instructions/git.html
> +          <a href="#shell">Інструкція по встановленню оболонки</a>).
Інструкція -> Інструкцію

2024-05-18 20:30 UTC, olexandr-konovalov commented on _includes/install_instructions/git.html
> +          доведеться  натиснути Control та клацнути правою кнопкою миші на
Мій попередній коментар був не зовсім повний - мається на увазі що арб доведеться клацнути правою кнопкою, або альтернативно натиснути Control та просто клацнути мишею. Справді, миша Apple не має ні лівої, ні правої кнопок.

2024-05-18 20:31 UTC, olexandr-konovalov commented on _includes/install_instructions/git.html
> +          нічого не буде, яка використовується за допомогою командного рядка.
Десь загубилося " оскільки Git є програмою"

2024-05-18 20:35 UTC, olexandr-konovalov commented on _includes/install_instructions/git.html
> +          допомогою менеджера пакетів вашого дистрибутива. Для запуску Debian/Ubuntu
Давайте напишемо 

У Debian/Ubuntu Linux використовуйте sudo apt-get install git, а у Fedora Linux - sudo dnf install git

2024-05-18 20:36 UTC, olexandr-konovalov commented on _includes/install_instructions/python.html
> +Видаліть третій абзац, на семінарі буде викладатись Python
загубилося "якщо"

2024-05-18 21:14 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +            не завершується на '/bash' , вашою типовою оболонкою є щось інше.
видаліть зайвий пробіл перед комою

2024-05-18 21:17 UTC, olexandr-konovalov commented on _includes/swc/intro.html
> +  отримані знання для власних дослідницьких проблемах.
проблемах -> проблем

2024-05-18 21:22 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +            Щоб перевірити, чи є ваша типова оболонка Bash, введіть <code>echo $SHELL</code>
@VeronikaShevc поки що ще декілька разів "типова" використовується нижче - там теж за зразком треба змінити на "за замовчуванням" (мабуть можна сказати "стандартною оболонкою" але не "типовою"). Давайте змінимо усе на "за замовчуванням" - так буде правильно. А потім подумаємо про синоніми.

2024-05-18 21:23 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +          і натисніть клавішу <kbd>Return</kbd>, а потім перезавантажтеся, щоб зміни набули чинності.
перезавантажтеся -> перезавантажте компʼютер

2024-05-18 21:29 UTC, olexandr-konovalov commented
Дякую за свіжі зміни @VeronikaShevc! Все йде добре - я помітив усі запроновані та зроблені зміни як "resolved", щоб не заважали. Ще трохи виправлень, і буде готово!

2024-05-19 20:49 UTC, olexandr-konovalov commented
@VeronikaShevc - прогрес! ще трохи виправлень про оболонку за замовчуванням, та у реченні про "teach foundational computational and data science skills to researchers" - і буде готово!

2024-05-19 20:50 UTC, olexandr-konovalov requested changes

2024-05-19 20:50 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +          Типовою оболонкою, як правило, є Bash, і зазвичай немає потреби нічого встановлювати.
ще одна "типова оболонка" -> "оболонка за замовчуванням",  "оболонка, що використовується за замовчуванням" тощо

2024-05-19 20:50 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +          Щоб змінити типову оболонку на Bash, введіть <code>chsh -s /bin/bash</code>
ще одна "типова оболонка" -> "оболонка за замовчуванням",  "оболонка, що використовується за замовчуванням" тощо

2024-05-19 20:50 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +          Щоб змінити типове значення назад на Zsh, введіть <code>chsh -s /bin/zsh</code>, натисніть клавішу
ще одна "типова оболонка" -> "оболонка за замовчуванням",  "оболонка, що використовується за замовчуванням" тощо

2024-05-19 20:50 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +          Щоб змінити типову оболонку на Bash, введіть <code>chsh -s /bin/bash</code>
ще одна "типова оболонка" -> "оболонка за замовчуванням",  "оболонка, що використовується за замовчуванням" тощо

2024-05-19 20:50 UTC, olexandr-konovalov commented on _includes/install_instructions/shell.html
> +          Щоб змінити типове значення назад на Zsh, введіть <code>chsh -s /bin/zsh</code>, натисніть клавішу
ще одна "типова оболонка" -> "оболонка за замовчуванням",  "оболонка, що використовується за замовчуванням" тощо

2024-05-19 20:50 UTC, olexandr-konovalov commented on index.md
> +заглибитись у науки про дані.
@VeronikaShevc Тут буде краще перекласти за змістом, а не дословно. Як щодо:
"навчати науковців базовим навичкам досліджень за допомогою обчислювальних методів" ?

2024-05-20 17:15 UTC, VeronikaShevc commented on index.md
> +заглибитись у науки про дані.
Дякую. 
А що робити з "data science"? Просто незважати на це і тільки замінити на "навчати науковців базовим навичкам досліджень за допомогою обчислювальних методів"?

2024-05-20 17:25 UTC, olexandr-konovalov commented on index.md
> +заглибитись у науки про дані.
так!

2024-05-20 17:26 UTC, VeronikaShevc commented
Дякую
________________________________
От: Olexandr Konovalov ***@***.***>
Отправлено: 20 мая 2024 г. 18:25
Кому: ukrainian-carpentries/workshop-template ***@***.***>
Копия: Veronika Shevchenko ***@***.***>; Mention ***@***.***>
Тема: {Disarmed} Re: [ukrainian-carpentries/workshop-template] Translate workshop template into Ukrainian (PR #1)


@olexandr-konovalov commented on this pull request.

________________________________

In index.md<https://github.com/ukrainian-carpentries/workshop-template/pull/1#discussion_r1607052004>:

>  {% endcomment %}

 <p>
-<strong><a href="https://carpentries.org">The Carpentries</a></strong> project comprises the <a
-href="{{site.swc_site}}">Software Carpentry</a>, <a href="{{site.dc_site}}">Data Carpentry</a>, and
-<a href="{{site.lc_site}}">Library Carpentry</a> communities of Instructors, Trainers, Maintainers,
-helpers, and supporters who share a mission to teach foundational computational and data science
-skills to researchers.
+Проект <strong><a href="https://carpentries.org">Carpentries</a></strong> містить в собі <a
+href="{{site.swc_site}}">Software Carpentry</a>, <a href="{{site.dc_site}}">Data Carpentry</a>, та
+<a href="{{site.lc_site}}">Library Carpentry</a> спільноти інструкторів, тренерів, супроводжувачів, помічників і прихильників. Вони мають спільну місію — навчати дослідників базовим навичкам комп'ютерного обчислювання та
+заглибитись у науки про дані.


так!

—
Reply to this email directly, view it on GitHub<https://github.com/ukrainian-carpentries/workshop-template/pull/1#discussion_r1607052004>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BDGN3C7JF6SPB3DFONMFY4TZDIW2LAVCNFSM6AAAAABEXYYN32VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANRWGY3DONZSHE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/ukrainian-carpentries/workshop-template/pull/1#discussion_r1607052004", "url": "https://github.com/ukrainian-carpentries/workshop-template/pull/1#discussion_r1607052004", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

2024-05-20 17:33 UTC, olexandr-konovalov approved these changes
@VeronikaShevc дякую - https://veronikashevc.github.io/workshop-template/ виглядає добре, можемо тепер додати зміни до https://github.com/ukrainian-carpentries/workshop-template/

2024-05-21 14:13 UTC, merged

2024-05-21 16:25 UTC, olexandr-konovalov commented
Переклад вже можна побачити онлайн на https://ukrainian-carpentries.github.io/workshop-template/